set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/s_axi_lite_aresetn]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[2]}]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/s_axis_s2mm_aresetn]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/s_axis_s2mm_tvalid]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[12]}]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/state_read]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/reads_done_reg_i_2_n_1]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/m_axi_full_mm2s_done]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_wdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axi_lite_rdata[18]}]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/INIT_AXI_TXN]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[5]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[13]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[14]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[8]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[10]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[4]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[9]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[6]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[7]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[11]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[12]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[3]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/init_txn_ff]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/init_txn_ff2]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_wvalid]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_bvalid]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_awready]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_wready]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_awvalid]
set_property MARK_DEBUG true [get_nets system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_bready]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_wdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axi_full_rdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/m_axis_mm2s_tdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[24]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[30]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[25]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[9]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[26]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[29]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[27]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[28]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[31]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/User_DMA_0/s_axis_s2mm_tdata[23]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/User_DMA_0/m_axi_full_rdata[0]} {system_i/User_DMA_0/m_axi_full_rdata[1]} {system_i/User_DMA_0/m_axi_full_rdata[2]} {system_i/User_DMA_0/m_axi_full_rdata[3]} {system_i/User_DMA_0/m_axi_full_rdata[4]} {system_i/User_DMA_0/m_axi_full_rdata[5]} {system_i/User_DMA_0/m_axi_full_rdata[6]} {system_i/User_DMA_0/m_axi_full_rdata[7]} {system_i/User_DMA_0/m_axi_full_rdata[8]} {system_i/User_DMA_0/m_axi_full_rdata[9]} {system_i/User_DMA_0/m_axi_full_rdata[10]} {system_i/User_DMA_0/m_axi_full_rdata[11]} {system_i/User_DMA_0/m_axi_full_rdata[12]} {system_i/User_DMA_0/m_axi_full_rdata[13]} {system_i/User_DMA_0/m_axi_full_rdata[14]} {system_i/User_DMA_0/m_axi_full_rdata[15]} {system_i/User_DMA_0/m_axi_full_rdata[16]} {system_i/User_DMA_0/m_axi_full_rdata[17]} {system_i/User_DMA_0/m_axi_full_rdata[18]} {system_i/User_DMA_0/m_axi_full_rdata[19]} {system_i/User_DMA_0/m_axi_full_rdata[20]} {system_i/User_DMA_0/m_axi_full_rdata[21]} {system_i/User_DMA_0/m_axi_full_rdata[22]} {system_i/User_DMA_0/m_axi_full_rdata[23]} {system_i/User_DMA_0/m_axi_full_rdata[24]} {system_i/User_DMA_0/m_axi_full_rdata[25]} {system_i/User_DMA_0/m_axi_full_rdata[26]} {system_i/User_DMA_0/m_axi_full_rdata[27]} {system_i/User_DMA_0/m_axi_full_rdata[28]} {system_i/User_DMA_0/m_axi_full_rdata[29]} {system_i/User_DMA_0/m_axi_full_rdata[30]} {system_i/User_DMA_0/m_axi_full_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/User_DMA_0/m_axi_full_wdata[0]} {system_i/User_DMA_0/m_axi_full_wdata[1]} {system_i/User_DMA_0/m_axi_full_wdata[2]} {system_i/User_DMA_0/m_axi_full_wdata[3]} {system_i/User_DMA_0/m_axi_full_wdata[4]} {system_i/User_DMA_0/m_axi_full_wdata[5]} {system_i/User_DMA_0/m_axi_full_wdata[6]} {system_i/User_DMA_0/m_axi_full_wdata[7]} {system_i/User_DMA_0/m_axi_full_wdata[8]} {system_i/User_DMA_0/m_axi_full_wdata[9]} {system_i/User_DMA_0/m_axi_full_wdata[10]} {system_i/User_DMA_0/m_axi_full_wdata[11]} {system_i/User_DMA_0/m_axi_full_wdata[12]} {system_i/User_DMA_0/m_axi_full_wdata[13]} {system_i/User_DMA_0/m_axi_full_wdata[14]} {system_i/User_DMA_0/m_axi_full_wdata[15]} {system_i/User_DMA_0/m_axi_full_wdata[16]} {system_i/User_DMA_0/m_axi_full_wdata[17]} {system_i/User_DMA_0/m_axi_full_wdata[18]} {system_i/User_DMA_0/m_axi_full_wdata[19]} {system_i/User_DMA_0/m_axi_full_wdata[20]} {system_i/User_DMA_0/m_axi_full_wdata[21]} {system_i/User_DMA_0/m_axi_full_wdata[22]} {system_i/User_DMA_0/m_axi_full_wdata[23]} {system_i/User_DMA_0/m_axi_full_wdata[24]} {system_i/User_DMA_0/m_axi_full_wdata[25]} {system_i/User_DMA_0/m_axi_full_wdata[26]} {system_i/User_DMA_0/m_axi_full_wdata[27]} {system_i/User_DMA_0/m_axi_full_wdata[28]} {system_i/User_DMA_0/m_axi_full_wdata[29]} {system_i/User_DMA_0/m_axi_full_wdata[30]} {system_i/User_DMA_0/m_axi_full_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 20 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[0]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[1]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[2]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[3]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[4]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[5]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[6]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[7]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[8]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[9]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[10]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[11]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[12]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[13]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[14]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[15]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[16]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[17]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[18]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/burst_count[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[0]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[1]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[2]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[3]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[4]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[5]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[6]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[7]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[8]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[9]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[10]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[11]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[12]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[13]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[14]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[15]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[16]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[17]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[18]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[19]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[20]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[21]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[22]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/read_burst_counter_reg[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[0]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[1]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[2]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[3]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[4]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[5]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[6]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[7]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[8]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[9]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[10]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[11]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[12]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[13]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[14]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[15]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[16]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[17]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[18]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[19]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[20]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[21]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[22]} {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/write_burst_counter_reg[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {system_i/User_DMA_0/m_axis_mm2s_tdata[0]} {system_i/User_DMA_0/m_axis_mm2s_tdata[1]} {system_i/User_DMA_0/m_axis_mm2s_tdata[2]} {system_i/User_DMA_0/m_axis_mm2s_tdata[3]} {system_i/User_DMA_0/m_axis_mm2s_tdata[4]} {system_i/User_DMA_0/m_axis_mm2s_tdata[5]} {system_i/User_DMA_0/m_axis_mm2s_tdata[6]} {system_i/User_DMA_0/m_axis_mm2s_tdata[7]} {system_i/User_DMA_0/m_axis_mm2s_tdata[8]} {system_i/User_DMA_0/m_axis_mm2s_tdata[9]} {system_i/User_DMA_0/m_axis_mm2s_tdata[10]} {system_i/User_DMA_0/m_axis_mm2s_tdata[11]} {system_i/User_DMA_0/m_axis_mm2s_tdata[12]} {system_i/User_DMA_0/m_axis_mm2s_tdata[13]} {system_i/User_DMA_0/m_axis_mm2s_tdata[14]} {system_i/User_DMA_0/m_axis_mm2s_tdata[15]} {system_i/User_DMA_0/m_axis_mm2s_tdata[16]} {system_i/User_DMA_0/m_axis_mm2s_tdata[17]} {system_i/User_DMA_0/m_axis_mm2s_tdata[18]} {system_i/User_DMA_0/m_axis_mm2s_tdata[19]} {system_i/User_DMA_0/m_axis_mm2s_tdata[20]} {system_i/User_DMA_0/m_axis_mm2s_tdata[21]} {system_i/User_DMA_0/m_axis_mm2s_tdata[22]} {system_i/User_DMA_0/m_axis_mm2s_tdata[23]} {system_i/User_DMA_0/m_axis_mm2s_tdata[24]} {system_i/User_DMA_0/m_axis_mm2s_tdata[25]} {system_i/User_DMA_0/m_axis_mm2s_tdata[26]} {system_i/User_DMA_0/m_axis_mm2s_tdata[27]} {system_i/User_DMA_0/m_axis_mm2s_tdata[28]} {system_i/User_DMA_0/m_axis_mm2s_tdata[29]} {system_i/User_DMA_0/m_axis_mm2s_tdata[30]} {system_i/User_DMA_0/m_axis_mm2s_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[0]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[1]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[2]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[3]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[4]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[5]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[6]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[7]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[8]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[9]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[10]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[11]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[12]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[13]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[14]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[15]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[16]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[17]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[18]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[19]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[20]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[21]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[22]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[23]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[24]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[25]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[26]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[27]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[28]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[29]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[30]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/m_axi_full_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 6 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[0]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[1]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[2]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[3]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[4]} {system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/fifo_cnt_reg__0[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {system_i/User_DMA_0/s_axis_s2mm_tdata[0]} {system_i/User_DMA_0/s_axis_s2mm_tdata[1]} {system_i/User_DMA_0/s_axis_s2mm_tdata[2]} {system_i/User_DMA_0/s_axis_s2mm_tdata[3]} {system_i/User_DMA_0/s_axis_s2mm_tdata[4]} {system_i/User_DMA_0/s_axis_s2mm_tdata[5]} {system_i/User_DMA_0/s_axis_s2mm_tdata[6]} {system_i/User_DMA_0/s_axis_s2mm_tdata[7]} {system_i/User_DMA_0/s_axis_s2mm_tdata[8]} {system_i/User_DMA_0/s_axis_s2mm_tdata[9]} {system_i/User_DMA_0/s_axis_s2mm_tdata[10]} {system_i/User_DMA_0/s_axis_s2mm_tdata[11]} {system_i/User_DMA_0/s_axis_s2mm_tdata[12]} {system_i/User_DMA_0/s_axis_s2mm_tdata[13]} {system_i/User_DMA_0/s_axis_s2mm_tdata[14]} {system_i/User_DMA_0/s_axis_s2mm_tdata[15]} {system_i/User_DMA_0/s_axis_s2mm_tdata[16]} {system_i/User_DMA_0/s_axis_s2mm_tdata[17]} {system_i/User_DMA_0/s_axis_s2mm_tdata[18]} {system_i/User_DMA_0/s_axis_s2mm_tdata[19]} {system_i/User_DMA_0/s_axis_s2mm_tdata[20]} {system_i/User_DMA_0/s_axis_s2mm_tdata[21]} {system_i/User_DMA_0/s_axis_s2mm_tdata[22]} {system_i/User_DMA_0/s_axis_s2mm_tdata[23]} {system_i/User_DMA_0/s_axis_s2mm_tdata[24]} {system_i/User_DMA_0/s_axis_s2mm_tdata[25]} {system_i/User_DMA_0/s_axis_s2mm_tdata[26]} {system_i/User_DMA_0/s_axis_s2mm_tdata[27]} {system_i/User_DMA_0/s_axis_s2mm_tdata[28]} {system_i/User_DMA_0/s_axis_s2mm_tdata[29]} {system_i/User_DMA_0/s_axis_s2mm_tdata[30]} {system_i/User_DMA_0/s_axis_s2mm_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {system_i/User_DMA_0/s_axi_lite_rdata[0]} {system_i/User_DMA_0/s_axi_lite_rdata[1]} {system_i/User_DMA_0/s_axi_lite_rdata[2]} {system_i/User_DMA_0/s_axi_lite_rdata[3]} {system_i/User_DMA_0/s_axi_lite_rdata[4]} {system_i/User_DMA_0/s_axi_lite_rdata[5]} {system_i/User_DMA_0/s_axi_lite_rdata[6]} {system_i/User_DMA_0/s_axi_lite_rdata[7]} {system_i/User_DMA_0/s_axi_lite_rdata[8]} {system_i/User_DMA_0/s_axi_lite_rdata[9]} {system_i/User_DMA_0/s_axi_lite_rdata[10]} {system_i/User_DMA_0/s_axi_lite_rdata[11]} {system_i/User_DMA_0/s_axi_lite_rdata[12]} {system_i/User_DMA_0/s_axi_lite_rdata[13]} {system_i/User_DMA_0/s_axi_lite_rdata[14]} {system_i/User_DMA_0/s_axi_lite_rdata[15]} {system_i/User_DMA_0/s_axi_lite_rdata[16]} {system_i/User_DMA_0/s_axi_lite_rdata[17]} {system_i/User_DMA_0/s_axi_lite_rdata[18]} {system_i/User_DMA_0/s_axi_lite_rdata[19]} {system_i/User_DMA_0/s_axi_lite_rdata[20]} {system_i/User_DMA_0/s_axi_lite_rdata[21]} {system_i/User_DMA_0/s_axi_lite_rdata[22]} {system_i/User_DMA_0/s_axi_lite_rdata[23]} {system_i/User_DMA_0/s_axi_lite_rdata[24]} {system_i/User_DMA_0/s_axi_lite_rdata[25]} {system_i/User_DMA_0/s_axi_lite_rdata[26]} {system_i/User_DMA_0/s_axi_lite_rdata[27]} {system_i/User_DMA_0/s_axi_lite_rdata[28]} {system_i/User_DMA_0/s_axi_lite_rdata[29]} {system_i/User_DMA_0/s_axi_lite_rdata[30]} {system_i/User_DMA_0/s_axi_lite_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {system_i/User_DMA_0/s_axi_lite_wdata[0]} {system_i/User_DMA_0/s_axi_lite_wdata[1]} {system_i/User_DMA_0/s_axi_lite_wdata[2]} {system_i/User_DMA_0/s_axi_lite_wdata[3]} {system_i/User_DMA_0/s_axi_lite_wdata[4]} {system_i/User_DMA_0/s_axi_lite_wdata[5]} {system_i/User_DMA_0/s_axi_lite_wdata[6]} {system_i/User_DMA_0/s_axi_lite_wdata[7]} {system_i/User_DMA_0/s_axi_lite_wdata[8]} {system_i/User_DMA_0/s_axi_lite_wdata[9]} {system_i/User_DMA_0/s_axi_lite_wdata[10]} {system_i/User_DMA_0/s_axi_lite_wdata[11]} {system_i/User_DMA_0/s_axi_lite_wdata[12]} {system_i/User_DMA_0/s_axi_lite_wdata[13]} {system_i/User_DMA_0/s_axi_lite_wdata[14]} {system_i/User_DMA_0/s_axi_lite_wdata[15]} {system_i/User_DMA_0/s_axi_lite_wdata[16]} {system_i/User_DMA_0/s_axi_lite_wdata[17]} {system_i/User_DMA_0/s_axi_lite_wdata[18]} {system_i/User_DMA_0/s_axi_lite_wdata[19]} {system_i/User_DMA_0/s_axi_lite_wdata[20]} {system_i/User_DMA_0/s_axi_lite_wdata[21]} {system_i/User_DMA_0/s_axi_lite_wdata[22]} {system_i/User_DMA_0/s_axi_lite_wdata[23]} {system_i/User_DMA_0/s_axi_lite_wdata[24]} {system_i/User_DMA_0/s_axi_lite_wdata[25]} {system_i/User_DMA_0/s_axi_lite_wdata[26]} {system_i/User_DMA_0/s_axi_lite_wdata[27]} {system_i/User_DMA_0/s_axi_lite_wdata[28]} {system_i/User_DMA_0/s_axi_lite_wdata[29]} {system_i/User_DMA_0/s_axi_lite_wdata[30]} {system_i/User_DMA_0/s_axi_lite_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[0]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[1]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[2]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[3]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[4]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[5]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[6]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[7]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[8]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[9]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[10]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[11]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[12]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[13]_i_2_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/FSM_onehot_state_ctrl[14]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list system_i/User_DMA_0/inst/INIT_AXI_TXN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/init_txn_ff]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/init_txn_ff2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_bready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_bvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/m_axi_full_mm2s_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_s2mm_inst/m_axi_full_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/reads_done_reg_i_2_n_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list system_i/User_DMA_0/s_axi_lite_aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/s_axis_s2mm_aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_S_AXIS_S2MM_inst/fifo_s2mm_inst/s_axis_s2mm_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list system_i/User_DMA_0/inst/User_DMA_v1_0_M_AXI_FULL_mm2s_inst/state_read]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
