# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_xbar_1/myip_v1_0_bfm_1_xbar_1.xci
# IP: The module: 'myip_v1_0_bfm_1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_xbar_1/myip_v1_0_bfm_1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myip_v1_0_bfm_1_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_xbar_1/myip_v1_0_bfm_1_xbar_1.xci
# IP: The module: 'myip_v1_0_bfm_1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_xbar_1/myip_v1_0_bfm_1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myip_v1_0_bfm_1_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
