webtalk_init -webtalk_dir D:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.sim/sim_1/behav/xsim/xsim.dir/myip_v1_0_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan  5 02:44:18 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b97a817d-141d-46d2-aada-35a7f4f9a0db" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4c404d95a55f422095d408513219dd8c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "64504_KB" -context "xsim\\usage"
webtalk_transmit -clientid 176487830 -regid "" -xml D:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.sim/sim_1/behav/xsim/xsim.dir/myip_v1_0_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.sim/sim_1/behav/xsim/xsim.dir/myip_v1_0_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/git/DMA-S2MM-and-MM2S-/project/DMA_simulation/DMA_simulation.sim/sim_1/behav/xsim/xsim.dir/myip_v1_0_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
