webtalk_init -webtalk_dir F:\\project\\DMA_video\\Miz_sys.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-01-16 20:02:04" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "spl3mh6vkj7kduqrdjh70laejg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.448 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1547639209607" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1547639209607"
webtalk_add_data -client sdk -key uid -value "1547639228942" -context "sdk\\\\bsp/1547639228942"
webtalk_add_data -client sdk -key hwid -value "1547639209607" -context "sdk\\\\bsp/1547639228942"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1547639228942"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1547639228942"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1547639228942"
webtalk_add_data -client sdk -key uid -value "1547639234300" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key hwid -value "1547639209607" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key bspid -value "1547639228942" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key projSize -value "213.12109375" -context "sdk\\\\application/1547639234300"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1547640123974"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1547640123974"
webtalk_transmit -clientid 905667286 -regid "" -xml F:\\project\\DMA_video\\Miz_sys.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\project\\DMA_video\\Miz_sys.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\project\\DMA_video\\Miz_sys.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
