vlib work
vlib riviera

vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v2_0_1
vlib riviera/axi_vip_v1_1_1
vlib riviera/processing_system7_vip_v1_0_3
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_12
vlib riviera/xlconstant_v1_1_3
vlib riviera/axis_infrastructure_v1_1_0
vlib riviera/fifo_generator_v13_2_1
vlib riviera/axis_data_fifo_v1_1_16
vlib riviera/xlconcat_v2_1_1
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/axi_data_fifo_v2_1_14
vlib riviera/axi_register_slice_v2_1_15
vlib riviera/axi_protocol_converter_v2_1_15

vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 riviera/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 riviera/axi_vip_v1_1_1
vmap processing_system7_vip_v1_0_3 riviera/processing_system7_vip_v1_0_3
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_12 riviera/proc_sys_reset_v5_0_12
vmap xlconstant_v1_1_3 riviera/xlconstant_v1_1_3
vmap axis_infrastructure_v1_1_0 riviera/axis_infrastructure_v1_1_0
vmap fifo_generator_v13_2_1 riviera/fifo_generator_v13_2_1
vmap axis_data_fifo_v1_1_16 riviera/axis_data_fifo_v1_1_16
vmap xlconcat_v2_1_1 riviera/xlconcat_v2_1_1
vmap generic_baseblocks_v2_1_0 riviera/generic_baseblocks_v2_1_0
vmap axi_data_fifo_v2_1_14 riviera/axi_data_fifo_v2_1_14
vmap axi_register_slice_v2_1_15 riviera/axi_register_slice_v2_1_15
vmap axi_protocol_converter_v2_1_15 riviera/axi_protocol_converter_v2_1_15

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"D:/xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"D:/xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ipshared/c239/hdl/User_DMA_v1_0_S_AXI_LITE.v" \
"../../../bd/system/ipshared/c239/src/User_DMA_v1_0_M_AXI_FULL_mm2s.v" \
"../../../bd/system/ipshared/c239/src/User_DMA_v1_0_M_AXI_FULL_s2mm.v" \
"../../../bd/system/ipshared/c239/hdl/User_DMA_v1_0_S_AXIS_S2MM.v" \
"../../../bd/system/ipshared/c239/hdl/User_DMA_v1_0_M_AXIS_MM2S.v" \
"../../../bd/system/ipshared/c239/src/fifo.v" \
"../../../bd/system/ipshared/c239/hdl/User_DMA_v1_0.v" \
"../../../bd/system/ip/system_User_DMA_0_0/sim/system_User_DMA_0_0.v" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_3  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/system/ip/system_rst_ps7_0_50M_0/sim/system_rst_ps7_0_50M_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/sim/bd_44e3.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/sim/bd_44e3_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/sim/bd_44e3_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/sim/bd_44e3_m00e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/sim/bd_44e3_sarn_0.sv" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/sim/bd_44e3_srn_0.sv" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/sim/bd_44e3_sawn_0.sv" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/sim/bd_44e3_swn_0.sv" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/sim/bd_44e3_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/sim/bd_44e3_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/sim/bd_44e3_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/sim/bd_44e3_s00sic_0.sv" \

vlog -work xlconstant_v1_1_3  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_0/sim/bd_44e3_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/sim/bd_44e3_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axi_smc_0/sim/system_axi_smc_0.v" \

vlog -work axis_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -93 \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axis_data_fifo_v1_1_16  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e3dd/hdl/axis_data_fifo_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_axis_data_fifo_0_0/sim/system_axis_data_fifo_0_0.v" \
"../../../bd/system/sim/system.v" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_15  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/1313/hdl" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/e2dd/hdl/verilog" "+incdir+../../../../DMA_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" "+incdir+D:/xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

